### ISSUE TITLE
Estruturação de Mídias (Imagens, Videos, Arquivos e afins)

### ISSUE THREAD

**Issue by arthurtavaresdev** [DanielHe4rt/basement-lms#11]
Na issue [#7](https://github.com/DanielHe4rt/basement-lms/issues/7#issuecomment-872616125 ), sugeri a criação de relação polifórmicas para a manipulação de Imagens.

Em seguida @NicolasPereira da Lib [laravel-medialibrary](https://spatie.be/docs/laravel-medialibrary/v9/introduction)

Abrir está issue, para discutimos sobre.

**Comment by arthurtavaresdev** [comment]
@NicolasPereira, Como dito anteriormente, nos cenários apresentados até o momento SIM e conta com muitos recursos uteis para o projeto no futuro.

O único ponto, que tenho duvidas é de que a parte de Midia é Vital para o projeto e a mesma está sendo manipulada por uma lib, dificultará mudanças que podem ser necessárias no futuro.

**Comment by NicolasPereira** [comment]
Acredito que devemos analisar o esforço, as libs da Spatie são bem boas e sempre recebem atualizações constantes. 

Acredito que para este primeiro momento do projeto é valido a implementação, principalmente visto o esforço da galera para criar algo

**Comment by svnn1** [comment]
Primeiramente temos que definir o que é realmente importante armazenar no banco de dados, vou deixar uma estrutura base abaixo:

```
media
    id - integer
    disk - string
    directory - string
    filename - string
    url - string
    mime_type - string
    size- integer

mediables
    media_id - integer
    mediable_type - string
    mediable_id - int
```

**Comment by arthurtavaresdev** [comment]
Caso utilizarmos a Lib, a mesma já nos entrega um schema fechado de banco de dados.

A primeiro momento, a mesma não parece ser permissiva a modificações.

**Comment by danielhe4rt** [comment]
Podemos implementar a lib do Spatie e seguir com ela. Não vejo muita ideia de criarmos algo nosso sendo que um import já resolveria.

O que vocês acham?

**Comment by NicolasPereira** [comment]
Eu penso pelo mesmo caminho, já utilizei essa lib da spatie em diversos projetos e nunca fiquei na mão

**Comment by danielhe4rt** [comment]
Tá feito, só fazer o review e fechar a issue.
