### ISSUE TITLE
Estruturação de aulas de um módulo

### ISSUE THREAD

**Issue by danielhe4rt** [DanielHe4rt/basement-lms#24]
Essa é a modelagem básica do que eu estou pensando em fazer para a aula de um módulo. 

```
lesson_types

id: int
name: string
slug: string
```
Seed: Video, Texto e Quiz

```
course_module_lessons:

id: uuid
title: string
description: string
type_id: int references id on lesson_types
content: text (polymorphic - url - text)
duration: time
```

Também estava vendo de utilizar o streaming da Azure para o projeto e deixar como padrão. Se tiverem alguma sugestão de como iremos fazer isso, favor deixar ai.

https://www.youtube.com/watch?v=Visn8ZBfSWs

**Comment by arthurtavaresdev** [comment]
time, não seria melhor obter via mutator ?

**Comment by arthurtavaresdev** [comment]
Peço que para a implementação do Streaming da Azure sejam considerados os Patterns [Template Method](https://refactoring.guru/pt-br/design-patterns/template-method) ou [Strategy](https://refactoring.guru/pt-br/design-patterns/strategy), para termos mais opções no futuro.

**Comment by NicolasPereira** [comment]
Pessoal, não tenho tanto conhecimento de boas práticas ou de como implementar isso da melhor maneira, mas estou lendo os materiais e termos discutidos aqui na issue.
