### ISSUE TITLE
Estruturação de Cursos

### ISSUE THREAD

**Issue by danielhe4rt** [DanielHe4rt/basement-lms#7]
Ideia de estruturação da pagina de cursos.

```
courses

id: id;
title: string (60);
subtitle: string (120);
description: text;
course_level_id: int references id course_levels;
cover_path: string; // References image on disk
paid: bool (false);
author_id: int references id users;

course_levels

id: int
name: string (20) 
```

**Comment by Zuruckt** [comment]
Acho que poderia ter uma funcionalidade de separação por tags

```
tags
    id: id;
    name: string (60);

course_tags (courses_tags? nao lembro direito)
    category_id: int references id on tags;
    course_id: int references id on courses;
```

**Comment by danielhe4rt** [comment]
As tags seriam referentes a coisas do curso? No caso, tecnologias? 

Tags: html, css, js, php etc?

**Comment by svnn1** [comment]
> As tags seriam referentes a coisas do curso? No caso, tecnologias?
> 
> Tags: html, css, js, php etc?

Se for isso que o @DanielHe4rt está pensando da para utilizar polimorfismo

```
courses
    id - integer
    name - string

tags
    id - integer
    name - string

taggables
    tag_id - integer
    taggable_id - integer
    taggable_type - string
```

**Comment by danielhe4rt** [comment]
Um campo importante a se pensar é sobre o status do curso, que pode ser feito por um seeder.

```
courses

status_id: referentes id on course_status

course_statuses

id: int
name: stirng

```
Tipos de status: Invisível, Em Planejamento, Gravando, Finalizado. 

Fica a ideia =)

**Comment by svnn1** [comment]
> Um campo importante a se pensar é sobre o status do curso, que pode ser feito por um seeder.
> 
> ```
> courses
> 
> status_id: referentes id on course_status
> 
> course_statuses
> 
> id: int
> name: stirng
> ```
> 
> Tipos de status: Invisível, Em Planejamento, Gravando, Finalizado.
> 
> Fica a ideia =)

Tambem pode ser um campo do tipo **enum**

```
courses
     status - enum -> Tipos de status: Invisível, Em Planejamento, Gravando, Finalizado.
```

**Comment by Zuruckt** [comment]
> As tags seriam referentes a coisas do curso? No caso, tecnologias?
> 
> Tags: html, css, js, php etc?

Isso

**Comment by Zuruckt** [comment]
Interessante também uma coluna `published_at: date` para indicar quando o curso foi publicado

**Comment by NicolasPereira** [comment]
Galera, posso puxar essa demanda aqui então ?

**Comment by Zuruckt** [comment]
Vai ser preciso terminar a #8 pra poder continuar, se não vai ter retrabalho no futuro pra adicionar a parte de permissoes pra gerenciar os cursos.

**Comment by arthurtavaresdev** [comment]
O atributo `cover_path`, pode gerar múltiplas implementações com o mesmo propósito. Toda e qualquer imagem de Cadastro deve ser adicionado via uma relação polifórmica, de "Midia".

Algo como, esta implementação:
```php
    public function up()
    {
        Schema::create('files', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('disk_name');
            $table->string('file_name');
            $table->integer('file_size');
            $table->string('content_type');
            $table->string('title')->nullable();
            $table->text('description')->nullable();
            $table->uuid('attachment_id')->index()->nullable();
            $table->string('attachment_type')->index()->nullable();
            $table->boolean('is_public')->default(true);
            $table->timestamps();
        });
    }
```

**Comment by NicolasPereira** [comment]
@arthurtavaresdev ideia boa, você acha que essa [lib](https://spatie.be/docs/laravel-medialibrary/v9/introduction) da spatie resolve o problema?

**Comment by arthurtavaresdev** [comment]
@NicolasPereira, nos cenários apresentados até o momento SIM e conta com muitos recursos uteis para o projeto no futuro.

O único ponto, que tenho duvidas é de que a parte de Midia é **Vital** para o projeto e a mesma está sendo manipulada por uma lib, dificultará mudanças que podem ser necessárias no futuro.

De qualquer forma, acredito que essa discussão deva ser movido para outra issue. (#11 )

**Comment by danielhe4rt** [comment]
Abri o PR em draft, favor darem uma olhada =)

#15
